---
- name: Add helm repos
  community.kubernetes.helm_repository:
    repo_name: "stable"
    repo_url: "https://kubernetes-sigs.github.io/aws-efs-csi-driver/"
  tags:
    - install
    - uninstall
    - upgrade

- name: Deploy efs-provisioner
  community.kubernetes.helm:
    name: "{{ efs_name }}"
    chart_ref: "files/efs-provisioner-{{ efs_chart_version }}.tgz"
    namespace: "{{ efs_namespace }}"
    values: "{{ efs_provisioner_config }}"
    chart_version: "{{ efs_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    update_repo_cache: true
    create_namespace: true
  tags:
    - install
    - upgrade

- name: Remove efs-provisioner
  community.kubernetes.helm:
    name: "{{ efs_name }}"
    namespace: "{{ efs_namespace }}"
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    values: "{{ efs_provisioner_config }}"
    state: absent
  tags:
    - uninstall

- name: Remove namespace
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ efs_namespace }}"
    wait: true
    state: absent
    kubeconfig: "{{ kubeconfig }}"
  tags:
    - uninstall
