# Copyright Â© 2020-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
## Multi-tenant

# Updating HOST to remove https
V4_CFG_CR_URL: https://cr.sas.com
V4_CFG_CR_HOST: '{{ V4_CFG_CR_URL | regex_replace("^https?:\/\/(.*)\/?", "\1") }}'

V4_CFG_CR_USER: null
V4_CFG_CR_PASSWORD: null

# Multi-tenant is enabled within SAS Viya deployment
V4MT_ENABLE: false

# SAS Viya supports two modes of data isolation (schemaPerApplicationTenant and databasePerTenant) for tenant data.
# Set V4MT_MODE to either schema or database. schemaPerApplicationTenant Mode is enabled by default.
V4MT_MODE: schema

V4MT_TENANT_IDS: null

# Optional job parameter
V4MT_PROVIDER_PASSWORD: null

# CAS customization values
V4MT_TENANT_CAS_CUSTOMIZATION: {}
# Setting values for retry and delay to 60 seconds for Onboard and Offboard job
V4MT_ONBOARD_RETRY: 60
V4MT_ONBOARD_DELAY: 60
V4MT_OFFBOARD_RETRY: 60
V4MT_OFFBOARD_DELAY: 60
