# Copyright Â© 2020-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
- name: Message Broker - check sitedefault.yaml exists
  stat:
    path: "{{ DEPLOY_DIR }}/site-config/sitedefault.yaml"
  register: stat_result
  tags:
    - install
    - uninstall
    - update

- name: Message Broker - check message broker values present
  ansible.builtin.fail:
    msg: >
      Message Broker - Azure Service Bus enabled but one or all of the expected variables:
      V4_CFG_MESSAGE_BROKER_HOST, V4_CFG_MESSAGE_BROKER_NAME and V4_CFG_MESSAGE_BROKER_PASSWORD are missing.
  when:
    - V4_CFG_MESSAGE_BROKER_HOST is none or V4_CFG_MESSAGE_BROKER_NAME is none or V4_CFG_MESSAGE_BROKER_PASSWORD is none
  tags:
    - install
    - uninstall
    - update

- name: Update site-default with message broker details
  lineinfile:
    path: "{{ DEPLOY_DIR }}/site-config/sitedefault.yaml"
    line: "{{ item.line }}"
    state: present
    insertafter: EOF
  with_items:
    - { line: 'config/application/sas.event.arke.broker/type: {{ PROVIDER }}' }
    - { line: 'config/application/sas.event.arke.broker/host: {{ V4_CFG_MESSAGE_BROKER_HOST }}' }
    - { line: 'config/application/sas.event.arke.broker/port: 8000' }
    - { line: 'config/application/sas.event.arke.broker/username: {{ V4_CFG_MESSAGE_BROKER_NAME }}' }
    - { line: 'config/application/sas.event.arke.broker/password: {{ V4_CFG_MESSAGE_BROKER_PASSWORD }}' }
  when: stat_result.stat.exists
  tags:
    - install
    - uninstall
    - update

- name: Message Broker - check Rabbitmq configuration file is present
  stat:
    path: "{{ DEPLOY_DIR }}/sas-bases/examples/rabbitmq/configuration/rabbitmq-node-count.yaml"
  register: rabbitmq_config
  tags:
    - install
    - uninstall
    - update

- name: Message Broker - copy rabbitmq config file
  copy:
    src: "{{ DEPLOY_DIR }}/sas-bases/examples/rabbitmq/configuration/rabbitmq-node-count.yaml"
    dest: "{{ role_path }}/templates/transformers/rabbitmq-node-count.yaml"
    mode: "0660"
  when: rabbitmq_config.stat.exists
  tags:
    - install
    - uninstall
    - update

- name: Message Broker - scale Rabbitmq to 0 replicas
  replace:
    path: "{{ role_path }}/templates/transformers/rabbitmq-node-count.yaml"
    regexp: "{% raw %}{{ NUMBER-OF-NODES }}{% endraw %}"
    replace: "0"
  when: rabbitmq_config.stat.exists
  tags:
    - install
    - uninstall
    - update

- name: Message Broker - add resource
  overlay_facts:
    cadence_name: "{{ V4_CFG_CADENCE_NAME }}"
    cadence_number: "{{ V4_CFG_CADENCE_VERSION }}"
    existing: "{{ vdm_overlays }}"
    add:
      - { transformers: "rabbitmq-node-count.yaml", vdm: true}
  when: rabbitmq_config.stat.exists
  tags:
    - install
    - uninstall
    - update
