PROVIDER: custom #[azure|aws|gcp|custom]
NAMESPACE: null
CLUSTER_NAME: null
DEPLOY: True
DEPLOYMENT_OPERATOR_ENABLED: False

V4_CFG_LICENSE: null
V4_CFG_DEPLOYMENT_ASSETS: null
V4_CFG_ORDER_NUMBER: null
V4_CFG_CADENCE_NAME: lts
V4_CFG_CADENCE_VERSION: 2020.1

V4_CFG_CR_USER: null
V4_CFG_CR_PASSWORD: null
V4_CFG_CR_URL: https://cr.sas.com
V4_CFG_CR_HOST: '{{ V4_CFG_CR_URL | regex_replace("^https?:\/\/(.*)\/?", "\1") }}'

V4_CFG_SAS_API_KEY: null
V4_CFG_SAS_API_SECRET: null

V4_CFG_RWX_FILESTORE_ENDPOINT: null
V4_CFG_RWX_FILESTORE_PATH: '/export'
V4_CFG_RWX_FILESTORE_DATA_PATH: "{{ V4_CFG_RWX_FILESTORE_PATH | replace('/$', '') }}/{{ NAMESPACE }}/data"
V4_CFG_RWX_FILESTORE_HOMES_PATH: "{{ V4_CFG_RWX_FILESTORE_PATH | replace('/$', '') }}/{{ NAMESPACE }}/homes"
V4_CFG_RWX_FILESTORE_ASTORES_PATH: "{{ V4_CFG_RWX_FILESTORE_PATH | replace('/$', '') }}/{{ NAMESPACE }}/astores"
V4_CFG_RWX_FILESTORE_BIN_PATH: "{{ V4_CFG_RWX_FILESTORE_PATH | replace('/$', '') }}/{{ NAMESPACE }}/bin"

V4_CFG_STORAGECLASS: sas
V4_CFG_MANAGE_STORAGE: false

V4_CFG_DEPLOYMENT_URL_PREFIX: null
V4_CFG_DEPLOYMENT_URL_PORT: null
V4_CFG_INGRESS_FQDN: null
V4_CFG_INGRESS_TYPE: ingress

V4_CFG_TLS_MODE: "front-door" # other valid values are full-stack, ingress-only, and disabled
V4_CFG_TLS_CERT: null
V4_CFG_TLS_KEY: null
V4_CFG_TLS_TRUSTED_CA_CERTS: null
V4_CFG_TLS_GENERATOR: openssl # [cert-manager,openssl]

V4_CFG_CONSUL_ENABLE_LOADBALANCER: false
V4_CFG_EMBEDDED_LDAP_ENABLE: false
V4_CFG_SSSD: null
V4_CFG_SITEDEFAULT: "{{'files/sitedefault.yaml' if not V4MT_ENABLE else 'files/sitedefault-mt.yaml'}}"

V4_CFG_CAS_RAM: null
V4_CFG_CAS_CORES: null
V4_CFG_CAS_WORKER_COUNT: 1
V4_CFG_CAS_ENABLE_LOADBALANCER: false
V4_CFG_CAS_ENABLE_BACKUP_CONTROLLER: false
V4_CFG_CONNECT_ENABLE_LOADBALANCER: false
V4_CFG_CONNECT_FQDN: null
V4_CFG_CLUSTER_NODE_POOL_MODE: "standard"

# In theory the issuer name can be changed; however, there are a few overlays where this value is hard coded. See:
# - $deploy/sas-bases/overlays/cert-manager-issuer/resources.yaml
# - $deploy/sas-bases/overlays/network/ingress/security/generators/backend-tls-generators.yaml
# - $deploy/sas-bases/overlays/network/istio/security/generators/truststore-only-tls-generators.yaml
# therefore, we will not document this variable.
V4_CFG_CM_ISSUER_NAME: sas-viya-issuer

V4_CFG_CM_CERTIFICATE_DURATION: 17531
V4_CFG_CM_CERTIFICATE_ADDITIONAL_SAN_DNS: ""
V4_CFG_CM_CERTIFICATE_ADDITIONAL_SAN_IP: ""

V4_CFG_TLS_DURATION: "{{ V4_CFG_CM_CERTIFICATE_DURATION }}"
V4_CFG_TLS_ADDITIONAL_SAN_DNS: "{{ V4_CFG_CM_CERTIFICATE_ADDITIONAL_SAN_DNS }}"
V4_CFG_TLS_ADDITIONAL_SAN_IP: "{{ V4_CFG_CM_CERTIFICATE_ADDITIONAL_SAN_IP }}"

V4_ORDERS_CLI_VERSION: 1.1.0

V4_CFG_ELASTICSEARCH_ENABLE: true

## Cloud
V4_CFG_CLOUD_SERVICE_ACCOUNT_NAME: null
V4_CFG_CLOUD_SERVICE_ACCOUNT_AUTH: null

# Multi-Tenant
V4MT_ENABLE: false
# SAS Viya supports two modes of data isolation (schemaPerApplicationTenant and databasePerTenant) for tenant data.
# Set V4MT_MODE to either schema or database
V4MT_MODE: "schema"

V4MT_TENANT_IDS: null

internal_postgres: false
