---
- name: FileGenerator updates for tenant-specific resources
  when: V4MT_TENANT_IDS is search(tenant)
  tags:
    - onboard
  block:
    - name: Delete tenant-specific resource directories if present
      file:
        state: absent
        path: "{{ DEPLOY_DIR }}/site-config/multi-tenant/{{ tenant }}"
    - name: Create a new directory for each tenant under $deploy/site-config/multi-tenant/
      file:
        state: directory
        dest: "{{ DEPLOY_DIR }}/site-config/multi-tenant/{{ tenant }}"
        mode: "0770"
    - name: Copy - sas-programming-environment files
      copy:
        src: "{{ DEPLOY_DIR }}/sas-bases/examples/multi-tenant/sas-programming-environment/"
        dest: "{{ DEPLOY_DIR }}/site-config/multi-tenant/{{ tenant }}"
        mode: "0770"
    - name: List all the pod templates to be updated
      find:
        paths: "{{ DEPLOY_DIR }}/site-config/multi-tenant/{{ item }}"
        recurse: true
      register: result
    - name: Replace all occurrences of SAS-TENANT-ID with the ID of the tenant
      replace:
        path: "{{ outer_item.path }}"
        regexp: "{% raw %}{{ SAS-TENANT-ID }}{% endraw %}"
        replace: "{{ tenant }}"
      with_items: "{{ result.files }}"
      loop_control:
        loop_var: outer_item
